version: '3.8'

services:
  db:
    image: postgres:14
    container_name: mydatabase
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    restart: always

  backend:
    build:
      context: ./backend
    container_name: flask_app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 5001:5001
    depends_on:
      - db
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - ./streams:/app/streams
  
  nginx: 
    build:
      context: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./streams:/usr/share/nginx/html/streams
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
