from .frame_capture import capture_frames
from .pipeline import start_all_streams, stop_all_streams,start_individual_stream, stop_individual_stream
from .tasks import start_stream_task, start_yolo_detection_task